// @ts-check
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { buildBundle } from "../src/pack-skill.mjs";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const BUNDLE = path.join(ROOT, "dist", "budzie.skill");

test("committed dist/budzie.skill is in sync with the skills", () => {
  const committed = readFileSync(BUNDLE, "utf8");
  assert.equal(
    committed,
    buildBundle(ROOT),
    "dist/budzie.skill is stale; run `npm run pack` and commit the result"
  );
});

test("bundle carries the budzie frontmatter and every skill body", () => {
  const committed = readFileSync(BUNDLE, "utf8");
  assert.match(committed, /^<!-- Generated by src\/pack-skill\.mjs/);
  assert.match(committed, /\nname: budzie\n/);
  // One section per skill: bodies are joined with "\n\n---\n\n", so 8 skills
  // produce 7 separators. (The frontmatter close is "\n---\n\n" and does not
  // match this double-newline separator.)
  const separators = committed.split("\n\n---\n\n").length - 1;
  assert.equal(separators, 7);
  // Bodies reference the engine at src/, never the old scripts/ path.
  assert.ok(!committed.includes("scripts/"), "bundle must not reference scripts/");
});
