// @ts-check
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Package every Budzie skill into one deterministic, self-contained Markdown
 * file: `dist/budzie.skill`. This is the single-file drop-in for hosts that
 * take one instructions file instead of a skills tree. It is a committed
 * artifact, not an install-time build — `npm run pack` regenerates it and a
 * test asserts the commit stays in sync with the sources.
 *
 * budzie: plain concatenation, not a zip. A zip `.skill` would need a new
 * dependency or the platform `zip` CLI; upgrade to a zip packager only if a
 * host actually requires the archive layout.
 */

/** The repo root, relative to this file (`src/`). */
const ROOT = fileURLToPath(new URL("..", import.meta.url));

/** Header stamped on the generated bundle. No timestamp: output is deterministic. */
const HEADER =
  "<!-- Generated by src/pack-skill.mjs. Do not edit by hand. " +
  "Run `npm run pack` to refresh; a test asserts this file matches the skills. -->";

/**
 * Split a Markdown file into its YAML frontmatter block and body.
 * @param {string} text
 * @returns {{ frontmatter: string | null, body: string }}
 */
function splitFrontmatter(text) {
  if (!text.startsWith("---\n")) return { frontmatter: null, body: text };
  const end = text.indexOf("\n---\n", 4);
  if (end === -1) return { frontmatter: null, body: text };
  return {
    frontmatter: text.slice(4, end),
    body: text.slice(end + 5).replace(/^\n+/, ""),
  };
}

/**
 * List skill directory names (those holding a `SKILL.md`), sorted for a
 * deterministic bundle. The primary `budzie` skill is emitted first.
 * @param {string} root
 * @returns {string[]}
 */
function skillDirs(root) {
  const skillsRoot = path.join(root, "skills");
  const names = readdirSync(skillsRoot, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((n) => {
      try {
        readFileSync(path.join(skillsRoot, n, "SKILL.md"));
        return true;
      } catch {
        return false;
      }
    })
    .sort();
  return ["budzie", ...names.filter((n) => n !== "budzie")];
}

/**
 * Build the single-file bundle string from the on-disk skills.
 * @param {string} [root] - Repo root; defaults to the package root.
 * @returns {string}
 */
export function buildBundle(root = ROOT) {
  const dirs = skillDirs(root);
  const primary = splitFrontmatter(
    readFileSync(path.join(root, "skills", "budzie", "SKILL.md"), "utf8")
  );
  const sections = dirs.map((name) => {
    const raw = readFileSync(
      path.join(root, "skills", name, "SKILL.md"),
      "utf8"
    );
    return splitFrontmatter(raw).body.trimEnd();
  });
  const parts = [
    HEADER,
    primary.frontmatter ? `---\n${primary.frontmatter}\n---` : null,
    sections.join("\n\n---\n\n"),
  ].filter(Boolean);
  return parts.join("\n\n") + "\n";
}

/**
 * Write the bundle to `dist/budzie.skill`.
 * @param {string} [root]
 * @returns {string} The path written.
 */
export function writeBundle(root = ROOT) {
  const dir = path.join(root, "dist");
  mkdirSync(dir, { recursive: true });
  const file = path.join(dir, "budzie.skill");
  writeFileSync(file, buildBundle(root));
  return file;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const file = writeBundle();
  process.stdout.write(`Wrote ${path.relative(process.cwd(), file)}\n`);
}
